---
apiVersion: v1
kind: Service
metadata:
  name: nova-api
spec:
  ports:
  - name: nova-api1
    port: 8774
    protocol: TCP
    targetPort: 8774
  - name: nova-api2
    port: 8775
    protocol: TCP
    targetPort: 8775
  selector:
    app: nova-api