---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: network-node
spec:
  template:
    metadata:
      labels:
        app: network-node
      name: network-node
      namespace: default
    spec:
      hostPID: true
      nodeSelector:
        non-persistent-control: 'yes'
      securityContext:
        runAsUser: 0
      hostNetwork: true
      dnsPolicy: ClusterFirst
      volumes:
        - name: lib-modules
          hostPath:
            path: /lib/modules
        - name: var-lib-nova
          hostPath:
            path: /var/lib/nova
        - name: var-lib-libvirt
          hostPath:
            path: /var/lib/libvirt
        - name: run
          hostPath:
            path: /run
        - name: resolv
          configMap:
            name: openstack-resolvconf
            items:
              - key: resolv.conf
                path: resolv.conf

        - name: cgroup
          hostPath:
            path: /sys/fs/cgroup
        - name: socket
          emptyDir: {}
        - name: ip
          hostPath:
            path: /sbin/ip
      containers:
        - name: neutron-openvswitch-agent
          command:
            - bash
            - "-c"
            - >-
              ovs-vsctl add-br br-ex

              sudo -E -u neutron kolla_start
          securityContext:
            privileged: true
          image: {{image_ovs_agent}}
          env:
            - name: KOLLA_SKIP_EXTEND_START
              value: ""
            - name: KOLLA_CONFIG_STRATEGY
              value: COPY_ONCE
            - name: KOLLA_CONFIG
              value: '{"command": "kolla_mesos_start","config_files":[{"source": "zk://{{zk_host}}/kolla/common/kolla_mesos_start.py","dest": "/usr/local/bin/kolla_mesos_start","owner": "root","perm": "0755"}]}'
            - name: KOLLA_LOGLEVEL
              value: info
            - name: KOLLA_ZK_HOSTS
              value: {{zk_host}}
            - name: KOLLA_PRIVATE_INTERFACE
              value: {{private_interface}}
            - name: KOLLA_PUBLIC_INTERFACE
              value: {{public_interface}}
            - name: ZK_APP_ID
              value: /root/openstack/neutron/neutron-openvswitch-agent
          volumeMounts:
            - mountPath: /etc/resolv
              name: resolv
            - mountPath: /lib/modules
              name: lib-modules
              readOnly: true
            - mountPath: /run
              name: run
          lifecycle:
            postStart:
              exec:
                command:
                  - "cp"
                  - "/etc/resolv/resolv.conf"
                  - "/etc/resolv.conf"

        - name: neutron-dhcp-agent
          securityContext:
            privileged: true
          image: {{image_neutron_dhcp}}
          env:
            - name: KOLLA_SKIP_EXTEND_START
              value: ""
            - name: KOLLA_CONFIG_STRATEGY
              value: COPY_ONCE
            - name: KOLLA_CONFIG
              value: '{"command": "kolla_mesos_start","config_files":[{"source": "zk://{{zk_host}}/kolla/common/kolla_mesos_start.py","dest": "/usr/local/bin/kolla_mesos_start","owner": "root","perm": "0755"}]}'
            - name: KOLLA_LOGLEVEL
              value: info
            - name: KOLLA_ZK_HOSTS
              value: {{zk_host}}
            - name: KOLLA_PRIVATE_INTERFACE
              value: {{private_interface}}
            - name: KOLLA_PUBLIC_INTERFACE
              value: {{public_interface}}
            - name: ZK_APP_ID
              value: /root/openstack/neutron/neutron-dhcp-agent
          volumeMounts:
            - mountPath: /etc/resolv
              name: resolv
            - mountPath: /lib/modules
              name: lib-modules
              readOnly: true
            - mountPath: /run
              name: run
            - mountPath: /var/lib/neutron/kolla/
              name: socket
            - mountPath: /usr/sbin/ip
              name: ip
          lifecycle:
            postStart:
              exec:
                command:
                  - "cp"
                  - "/etc/resolv/resolv.conf"
                  - "/etc/resolv.conf"

        - name: neutron-metadata-agent
          securityContext:
            privileged: true
          image: {{image_neutron_metadata}}
          env:
            - name: KOLLA_SKIP_EXTEND_START
              value: ""
            - name: KOLLA_CONFIG_STRATEGY
              value: COPY_ONCE
            - name: KOLLA_CONFIG
              value: '{"command": "kolla_mesos_start","config_files":[{"source": "zk://{{zk_host}}/kolla/common/kolla_mesos_start.py","dest": "/usr/local/bin/kolla_mesos_start","owner": "root","perm": "0755"}]}'
            - name: KOLLA_LOGLEVEL
              value: info
            - name: KOLLA_ZK_HOSTS
              value: {{zk_host}}
            - name: KOLLA_PRIVATE_INTERFACE
              value: {{private_interface}}
            - name: KOLLA_PUBLIC_INTERFACE
              value: {{public_interface}}
            - name: ZK_APP_ID
              value: /root/openstack/neutron/neutron-metadata-agent
          volumeMounts:
            - mountPath: /etc/resolv
              name: resolv
            - mountPath: /lib/modules
              name: lib-modules
              readOnly: true
            - mountPath: /run
              name: run
            - mountPath: /var/lib/neutron/kolla/
              name: socket
          lifecycle:
            postStart:
              exec:
                command:
                  - "cp"
                  - "/etc/resolv/resolv.conf"
                  - "/etc/resolv.conf"

        - name: openvswitch-db-server
          securityContext:
            privileged: true
          image: {{image_ovs_db}}
          env:
            - name: KOLLA_SKIP_EXTEND_START
              value: ""
            - name: KOLLA_CONFIG_STRATEGY
              value: COPY_ONCE
            - name: KOLLA_CONFIG
              value: '{"command": "kolla_mesos_start","config_files":[{"source": "zk://{{zk_host}}/kolla/common/kolla_mesos_start.py","dest": "/usr/local/bin/kolla_mesos_start","owner": "root","perm": "0755"}]}'
            - name: KOLLA_LOGLEVEL
              value: info
            - name: KOLLA_ZK_HOSTS
              value: {{zk_host}}
            - name: KOLLA_PRIVATE_INTERFACE
              value: {{private_interface}}
            - name: KOLLA_PUBLIC_INTERFACE
              value: {{public_interface}}
            - name: ZK_APP_ID
              value: /root/infra/openvswitch/openvswitch-db
          volumeMounts:
            - mountPath: /etc/resolv
              name: resolv
            - mountPath: /run
              name: run
          lifecycle:
            postStart:
              exec:
                command:
                  - "cp"
                  - "/etc/resolv/resolv.conf"
                  - "/etc/resolv.conf"

        - name: openvswitch-vswitchd
          securityContext:
            privileged: true
          image: {{image_ovs_vswitchd}}
          env:
            - name: KOLLA_SKIP_EXTEND_START
              value: ""
            - name: KOLLA_CONFIG_STRATEGY
              value: COPY_ONCE
            - name: KOLLA_CONFIG
              value: '{"command": "kolla_mesos_start","config_files":[{"source": "zk://{{zk_host}}/kolla/common/kolla_mesos_start.py","dest": "/usr/local/bin/kolla_mesos_start","owner": "root","perm": "0755"}]}'
            - name: KOLLA_LOGLEVEL
              value: info
            - name: KOLLA_ZK_HOSTS
              value: {{zk_host}}
            - name: KOLLA_PRIVATE_INTERFACE
              value: {{private_interface}}
            - name: KOLLA_PUBLIC_INTERFACE
              value: {{public_interface}}
            - name: ZK_APP_ID
              value: /root/infra/openvswitch/openvswitch-vswitchd
          volumeMounts:
            - mountPath: /etc/resolv
              name: resolv
            - mountPath: /lib/modules
              name: lib-modules
              readOnly: true
            - mountPath: /run
              name: run
          lifecycle:
            postStart:
              exec:
                command:
                  - "cp"
                  - "/etc/resolv/resolv.conf"
                  - "/etc/resolv.conf"

        - name: neutron-l3-agent
          securityContext:
            privileged: true
          image: {{image_neutron_l3}}
          env:
            - name: KOLLA_SKIP_EXTEND_START
              value: ""
            - name: KOLLA_CONFIG_STRATEGY
              value: COPY_ONCE
            - name: KOLLA_CONFIG
              value: '{"command": "kolla_mesos_start","config_files":[{"source": "zk://{{zk_host}}/kolla/common/kolla_mesos_start.py","dest": "/usr/local/bin/kolla_mesos_start","owner": "root","perm": "0755"}]}'
            - name: KOLLA_LOGLEVEL
              value: info
            - name: KOLLA_ZK_HOSTS
              value: {{zk_host}}
            - name: KOLLA_PRIVATE_INTERFACE
              value: {{private_interface}}
            - name: KOLLA_PUBLIC_INTERFACE
              value: {{public_interface}}
            - name: ZK_APP_ID
              value: /root/openstack/neutron/neutron-l3-agent
          volumeMounts:
            - mountPath: /etc/resolv
              name: resolv
            - mountPath: /lib/modules
              name: lib-modules
              readOnly: true
            - mountPath: /run
              name: run
            - mountPath: /var/lib/neutron/kolla/
              name: socket
            - mountPath: /usr/sbin/ip
              name: ip
          lifecycle:
            postStart:
              exec:
                command:
                  - "cp"
                  - "/etc/resolv/resolv.conf"
                  - "/etc/resolv.conf"
