---
apiVersion: v1
kind: Service
metadata:
  name: nova-novncproxy
spec:
  ports:
  - name: nova-novncproxy
    port: 6080
    protocol: TCP
    targetPort: 6080
    nodePort: {{node_port}}
  type: NodePort
  selector:
    app: nova-novncproxy
