apiVersion: v1
kind: Pod
metadata:
  name: redis
spec:
  containers:
  - name: redis
    image: kubernetes/redis:v1
    env:
    - name: MASTER
      value: "true"
    ports:
    - containerPort: 6379
    resources:
      limits:
        cpu: "0.1"
    volumeMounts:
      - mountPath: /etc/resolv
        name: config
    lifecycle:
      postStart:
        exec:
          command:
            - "cp"
            - "/etc/resolv/resolv.conf"
            - "/etc/resolv.conf"
  volumes:
    - name: config
      configMap:
        name: openstack-resolvconf
        items:
        - key: resolv.conf
          path: resolv.conf
