---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: neutron_ansible_tasks
  name: neutron-init
spec:
  nodeSelector:
    non-persistent-control: 'yes'
  restartPolicy: OnFailure
  containers:
    - name: neutron-init
      command:
        - kolla_start
      image: quay.io/stackanetes/centos-binary-kolla-toolbox:2.0.0
      env:
        - name: KOLLA_SKIP_EXTEND_START
          value: ""
        - name: KOLLA_CONFIG_STRATEGY
          value: COPY_ONCE
        - name: KOLLA_CONFIG
          value: '{"command": "kolla_mesos_start","config_files":[{"source": "zk://{{zk_host}}/kolla/common/kolla_mesos_start.py","dest": "/usr/local/bin/kolla_mesos_start","owner": "root","perm": "0755"}]}'
        - name: KOLLA_LOGLEVEL
          value: info
        - name: KOLLA_ZK_HOSTS
          value: {{zk_host}}
        - name: KOLLA_PRIVATE_INTERFACE
          value: {{private_interface}}
        - name: KOLLA_PUBLIC_INTERFACE
          value: {{public_interface}}
        - name: ZK_APP_ID
          value: /root/openstack/neutron/neutron_ansible_tasks
        - name: ANSIBLE_LIBRARY
          value: /usr/share/ansible/
        - name: ANSIBLE_NOCOLOR
          value: "1"
      ports:
      - containerPort: 3306
        name: mariadb
        protocol: TCP
