---
apiVersion: v1
kind: Service
metadata:
  name: keystone-api
spec:
  ports:
  - name: keystone-api1
    port: 5000
    protocol: TCP
    targetPort: 5000
  - name: keystone-api2
    port: 35357
    protocol: TCP
    targetPort: 35357
  selector:
    app: keystone-api
