---
apiVersion: v1
kind: Service
metadata:
  name: horizon
spec:
  ports:
  - name: horizon1
    nodePort: {{http_nodePort}}
    port: 80
    protocol: TCP
    targetPort: 80
  - name: horizon2
    port: 443
    protocol: TCP
    targetPort: 443
  selector:
    app: horizon
  type: NodePort
