apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: horizon
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: horizon
      name: horizon
    spec:
      nodeSelector:
        non-persistent-control: 'yes'
      containers:
        - name: horizon
          securityContext:
            privileged: true
          image: {{image}}
          env:
            - name: KOLLA_SKIP_EXTEND_START
              value: ""
            - name: KOLLA_CONFIG_STRATEGY
              value: COPY_ONCE
            - name: KOLLA_CONFIG
              value: '{"command": "kolla_mesos_start","config_files":[{"source": "zk://{{zk_host}}/kolla/common/kolla_mesos_start.py","dest": "/usr/local/bin/kolla_mesos_start","owner": "root","perm": "0755"}]}'
            - name: KOLLA_LOGLEVEL
              value: info
            - name: KOLLA_ZK_HOSTS
              value: {{zk_host}}
            - name: KOLLA_PRIVATE_INTERFACE
              value: {{private_interface}}
            - name: KOLLA_PUBLIC_INTERFACE
              value: {{public_interface}}
            - name: ZK_APP_ID
              value: /root/openstack/horizon/horizon
          ports:
          - containerPort: 8774
            name: horizon1
            protocol: TCP
          - containerPort: 443
            name: horizon2
            protocol: TCP
